name: Intro - Scheduled Workflow

on:
    workflow_dispatch:
    schedule:
      - cron: '0 9 * * 1' # Every Monday at 9 AM
    push:
      paths:
        - '.github/workflows/intro-scheduled-workflow.yml'

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Display current date and time
        run: echo "The current date and time is $(date)"
